### ISSUE TITLE
How to use this project.

### ISSUE THREAD

**Issue by darmie** [gnustep/libs-xcode#1]
Please can you provide a guide on how to use this project.. Would be cool if i can use it to build xcode projects on a Linux/Ubuntu platform. 

Thanks in advance!

**Comment by gnustep** [comment]
Hey Darmie.  If you look at buildtool it should give an excellent example.  The purpose of the xcode library is to parse an xcode project and extract information from it as well as to be able to build it per the rules defined in the project file.

In order to build it you will need to have built and installed gnustep either from source or from the ubuntu packages.  I have not tested building agains the packages, but I have no reason to believe that it wouldn't work.

**Comment by gcasa** [comment]
> Please can you provide a guide on how to use this project.. Would be cool if i can use it to build xcode projects on a Linux/Ubuntu platform.
> 
> Thanks in advance!

Build libs-xcode and install it
Build buildtool and install it
go to a directory containing an xcodeproj
type bulldtool
it should build the project
you will end up with a build directory. :)

GC

**Comment by gcasa** [comment]
Added a quick blurb in the README on how to use this project.
